version: '3.7'

services:
  electrum:
    build:
      context: .
      args:
        - ELECTRUM_VERSION=4.4.5
    ports:
      - 127.0.0.1:7000:7000
    environment:
      - ELECTRUM_USER=electrum
      - ELECTRUM_PASSWORD=changeme
      - ELECTRUM_NETWORK=testnet
      - ELECTRUM_PROXY=socks5:localhost:9050 # example: socks5:localhost:9050
      - ELECTRUM_TOR_SERVER=electrums3lojbuj.onion:50001:t # example: electrums3lojbuj.onion:50001:t
    container_name: electrum
    image: slashfast/docker-electrum-daemon
    volumes:
      - ../electrum:/data
